spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: bank
        jdbc:
          batch_size: 20
        order_updates: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bank-app-db
    username: postgres
    password: postgres
  data:
    web:
      pageable:
        one-indexed-parameters: true

  liquibase:
    change-log: classpath:/db/db.changelog-master.yaml

application:
  security:
    jwt:
      secret-key: S2pjZHJpdmFPUkVlYWtqR21iT3prSmwycmdkdjh3ZE8=
      expiration: 86400000
      refresh-expiration: 86400000
  encryption:
    key: d3JtUjlIR1kyeFluNmF6VDUyd1lDbTZPNkFxQUw3RVA=

logging:
  level:
    org:
      springframework:
        security: DEBUG

server:
  error:
    include-message: always
