spring:
  jpa:
    properties:
      hibernate:
        default_schema: bank
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/bank-app-db
    username: postgres
    password: postgres

  liquibase:
    change-log: classpath:/db/db.changelog-master.yaml

application:
  security:
    jwt:
      secret-key: S2pjZHJpdmFPUkVlYWtqR21iT3prSmwycmdkdjh3ZE8=
      expiration: 86400000
      refresh-expiration: 86400000

logging:
  level:
    org:
      springframework:
        security: DEBUG

#Что нужно сделать:
#  - Указать настройки подключения к базе данных.
#  - Указать порт приложения.
#  - Настроить параметры безопасности и JWT.
#  - Включить Swagger UI.
